//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticaProdutos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoTransacao
    {
        public TipoTransacao()
        {
            this.Transacao = new HashSet<Transacao>();
        }
    
        public int Id { get; set; }
        public string Tipo { get; set; }
    
        public virtual ICollection<Transacao> Transacao { get; set; }
    }
}
